name: fluffygate
description: Dead simple push gateway for Matrix to Firebase Cloud Messaging written in Dart.
version: 1.0.2
repository: https://github.com/krille-chan/fluffygate

environment:
  sdk: ^3.1.1

dependencies:
  args: ^2.5.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  yaml: ^3.1.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
